In [1]:
import numpy as np

In [2]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [3]:
# numpy主要包括：
# 一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组，称为 ndarray(N-dimensional array object)
# 用于对整组数据进行快速运算的标准数学函数:ufunc(universal function object)
# 实用的线性代数、傅里叶变换和随机数生成函数。 
# NumPy和稀疏矩阵的运算包Scipy配合使用更加方便。

In [4]:
# ndarray的创建
# array函数:接收一个普通的python序列，并将其转换为ndarray 
# zeros函数:创建指定长度或者形状的全零数组。 
# ones函数:创建指定长度或者形状的全1数组。
# empty函数:创建一个没有任何具体值的数组(准确地说是创建一些未初始化 的ndarray多维数组)

In [5]:
#  array函数
list1= [1,2,3,4,5]
np.array(list1)

array([1, 2, 3, 4, 5])

In [6]:
# 二维
list2=[[1,2,3],[4,5,6]]
np.array(list2)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 使用元祖
tup1 = (1,2,3,4)
np.array(tup1)

array([1, 2, 3, 4])

In [8]:
# 二维元祖
tup2=((1,2,3),(4,5,6))
np.array(tup2)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# zeros创建
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# ones创建
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# empty创建
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# 其他创建方式
# arange函数: 类似python的range函数，通过指定开始值、终值和步长来 创建一个一维数组，注意:最终创建的数组不包含终值
# linspace函数:通过指定开始值、终值和元素个数来创建一个一维数组， 数组的数据元素符合等差数列，可以通过endpoint关键字指定是否包含终 值，默认包含终值
# logspace函数:和linspace函数类似，不过创建的是等比数列数组
# 使用随机数填充数组，即使用numpy.random中的random()函数来创建 0-1之间的随机元素，数组包含的元素数量由参数决定

In [13]:
# arange函数
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.arange(15,20)

array([15, 16, 17, 18, 19])

In [15]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [16]:
np.arange(20,10,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [17]:
#linspace函数
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
# 0 10的0次方，2 10的2次方 生产5个
np.logspace(0,2,5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [19]:
np.random.random((3,2,3))

array([[[0.50787442, 0.31044095, 0.68875813],
        [0.28016029, 0.71002687, 0.29759545]],

       [[0.55898111, 0.52885932, 0.07378515],
        [0.27973493, 0.44214567, 0.73361401]],

       [[0.03133649, 0.63212325, 0.55014522],
        [0.00160637, 0.97410845, 0.36918798]]])

In [20]:
# 标准正态分布的
np.random.randn(3,3)

array([[-1.9567607 , -1.03743933, -1.77948851],
       [-0.78235948, -1.46926069,  0.96612352],
       [ 0.68582149,  0.71226067, -1.57550477]])

In [21]:
# 5个0-1的随机数
np.random.rand(5)

array([0.30226687, 0.31859367, 0.71225271, 0.99191141, 0.67679263])

In [22]:
# 0-10的随机
np.random.randint(1,10,(3,3))

array([[1, 5, 7],
       [3, 8, 6],
       [7, 2, 5]])

In [23]:
# 用reshape修改形状
arr = np.random.randint(1,10,(2,3,4))
arr

array([[[5, 2, 9, 9],
        [9, 9, 8, 5],
        [4, 1, 2, 9]],

       [[7, 9, 7, 2],
        [6, 7, 8, 2],
        [9, 5, 7, 9]]])

In [24]:
arr1 = arr.reshape(6,4)
arr1

array([[5, 2, 9, 9],
       [9, 9, 8, 5],
       [4, 1, 2, 9],
       [7, 9, 7, 2],
       [6, 7, 8, 2],
       [9, 5, 7, 9]])

In [25]:
# -1表示自动计算
arr2 = arr.reshape(-1,6)
arr2

array([[5, 2, 9, 9, 9, 9],
       [8, 5, 4, 1, 2, 9],
       [7, 9, 7, 2, 6, 7],
       [8, 2, 9, 5, 7, 9]])

In [26]:
help(np.where)

Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and input arrays are